// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCourse_FinalProject.Models;

#nullable disable

namespace WebCourse_FinalProject.Migrations
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebCourse_FinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Art"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Computer"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Cooking"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Language"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Self-Development"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sport"
                        });
                });

            modelBuilder.Entity("WebCourse_FinalProject.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ComapnyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 2,
                            ComapnyName = "ASAL",
                            CourseName = "HTML & CSS",
                            Duration = 16,
                            Location = "Nablus",
                            Price = 2500
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 1,
                            ComapnyName = "AAUP",
                            CourseName = "Engineering Drawing",
                            Duration = 16,
                            Location = "Nablus",
                            Price = 2500
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 6,
                            ComapnyName = "Fitness",
                            CourseName = "BasketBall",
                            Duration = 16,
                            Location = "Nablus",
                            Price = 2500
                        });
                });

            modelBuilder.Entity("WebCourse_FinalProject.Models.Course", b =>
                {
                    b.HasOne("WebCourse_FinalProject.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
